dependencies:
  - python
  - numpy
  - cartopy
  - pandas
  - scipy
  - pip
  - cmocean
  - geojson
  - geopandas
  - matplotlib
  - MetPy
  - python-dateutil
  - seaborn
  - tqdm
  - pygeos
  - descartes
  - pip:
    - odp-sdk
